"use client";

import React, { useState } from "react";
import { Lesson } from "@/types/curriculum";
import { InlineEditable } from "./InlineEditable";
import { Trash2, Sparkles, BookOpen } from "lucide-react";

interface LessonRowProps {
  lesson: Lesson;
  index: number;
  moduleId: string;
  topicId: string;
  onUpdate: (updates: Partial<Pick<Lesson, "title" | "description">>) => void;
  onDelete: () => void;
}

export function LessonRow({
  lesson,
  index,
  onUpdate,
  onDelete,
}: LessonRowProps) {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <div
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className="group relative flex items-start gap-3 p-3 rounded-lg border border-neutral-200/70 dark:border-neutral-800 bg-white/70 dark:bg-neutral-900/50 hover:bg-white dark:hover:bg-neutral-900 hover:border-neutral-300 dark:hover:border-neutral-700 transition-all duration-150 shadow-[0_1px_2px_rgba(0,0,0,0.02)] hover:shadow-sm"
    >
      {/* Icon / Status indicator */}
      <div className="mt-0.5 flex-shrink-0 flex items-center justify-center w-6 h-6 rounded-md bg-neutral-100 dark:bg-neutral-800 text-neutral-500 group-hover:text-[#EC8601] transition-colors">
        <BookOpen className="w-3.5 h-3.5" />
      </div>

      {/* Lesson Content Area */}
      <div className="flex-grow min-w-0 space-y-1">
        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex-grow min-w-0">
            <InlineEditable
              value={lesson.title}
              onSave={(newTitle) => onUpdate({ title: newTitle })}
              placeholder="Enter lesson title..."
              textClassName="text-sm font-medium text-neutral-900 dark:text-neutral-100"
              inputClassName="text-sm font-medium"
            />
          </div>

          {/* Inferred badge */}
          {lesson.isInferred && (
            <span
              title="This lesson was inferred & generated by AI based on nursing context"
              className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border border-amber-200/60 dark:border-amber-800/40 select-none flex-shrink-0"
            >
              <Sparkles className="w-2.5 h-2.5 text-[#EC8601]" />
              AI Inferred
            </span>
          )}
        </div>

        {/* Lesson Description */}
        <InlineEditable
          value={lesson.description}
          onSave={(newDesc) => onUpdate({ description: newDesc })}
          placeholder="Click to add lesson description..."
          multiline={true}
          textClassName="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed"
          inputClassName="text-xs"
        />
      </div>

      {/* Delete Action Button */}
      <div className="flex-shrink-0 self-start mt-0.5">
        <button
          onClick={(e) => {
            e.stopPropagation();
            onDelete();
          }}
          className={`p-1.5 rounded text-neutral-400 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950/40 transition-all ${
            isHovered ? "opacity-100" : "opacity-0 group-hover:opacity-70"
          }`}
          title="Delete lesson"
          aria-label="Delete lesson"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    </div>
  );
}
