"use client";

import React, { useState } from "react";
import { Module, Topic, Lesson } from "@/types/curriculum";
import { TopicCard } from "./TopicCard";
import { InlineEditable } from "./InlineEditable";
import {
  ChevronDown,
  ChevronRight,
  Plus,
  Trash2,
  Sparkles,
  FolderOpen,
  AlertCircle,
} from "lucide-react";

interface ModuleCardProps {
  module: Module;
  moduleIndex: number;
  onUpdateModule: (updates: Partial<Pick<Module, "title" | "description">>) => void;
  onDeleteModule: () => void;
  onToggleCollapse: () => void;
  onAddTopic: () => void;
  onUpdateTopic: (
    topicId: string,
    updates: Partial<Pick<Topic, "title" | "description">>
  ) => void;
  onDeleteTopic: (topicId: string) => void;
  onToggleTopicCollapse: (topicId: string) => void;
  onAddLesson: (topicId: string) => void;
  onUpdateLesson: (
    topicId: string,
    lessonId: string,
    updates: Partial<Pick<Lesson, "title" | "description">>
  ) => void;
  onDeleteLesson: (topicId: string, lessonId: string) => void;
}

export function ModuleCard({
  module,
  moduleIndex,
  onUpdateModule,
  onDeleteModule,
  onToggleCollapse,
  onAddTopic,
  onUpdateTopic,
  onDeleteTopic,
  onToggleTopicCollapse,
  onAddLesson,
  onUpdateLesson,
  onDeleteLesson,
}: ModuleCardProps) {
  const [isHovered, setIsHovered] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const isCollapsed = module.isCollapsed ?? false;

  const totalLessons = module.topics.reduce(
    (sum, topic) => sum + topic.lessons.length,
    0
  );

  return (
    <div
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className="relative rounded-2xl border border-neutral-200/90 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-all duration-200 hover:shadow-md hover:border-neutral-300 dark:hover:border-neutral-700 overflow-hidden"
    >
      {/* Brand Accent Bar on Left */}
      <div className="absolute left-0 top-0 bottom-0 w-1.5 bg-[#EC8601]" />

      {/* Module Card Header */}
      <div className="p-5 sm:p-6 border-b border-neutral-100 dark:border-neutral-800/80 bg-neutral-50/40 dark:bg-neutral-900/30">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-start gap-3 flex-grow min-w-0">
            {/* Collapse/Expand button */}
            <button
              onClick={onToggleCollapse}
              className="mt-1 p-1.5 rounded-lg hover:bg-neutral-200/70 dark:hover:bg-neutral-800 text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-100 transition-colors flex-shrink-0"
              title={isCollapsed ? "Expand module" : "Collapse module"}
              aria-label={isCollapsed ? "Expand module" : "Collapse module"}
            >
              {isCollapsed ? (
                <ChevronRight className="w-5 h-5" />
              ) : (
                <ChevronDown className="w-5 h-5" />
              )}
            </button>

            <div className="flex-grow min-w-0 space-y-2">
              <div className="flex items-center gap-2.5 flex-wrap">
                {/* Module Badge */}
                <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-[#EC8601]/10 text-[#EC8601] border border-[#EC8601]/20 select-none flex-shrink-0">
                  <FolderOpen className="w-3.5 h-3.5" />
                  MODULE {moduleIndex + 1}
                </span>

                {/* Counter Badges */}
                <span className="text-xs text-neutral-400 dark:text-neutral-500">
                  {module.topics.length} {module.topics.length === 1 ? "topic" : "topics"} · {totalLessons} {totalLessons === 1 ? "lesson" : "lessons"}
                </span>

                {/* AI Inferred Badge */}
                {module.isInferred && (
                  <span
                    title="This module was inferred & generated by AI"
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border border-amber-200/60 dark:border-amber-800/40 select-none flex-shrink-0"
                  >
                    <Sparkles className="w-2.5 h-2.5 text-[#EC8601]" />
                    AI Inferred
                  </span>
                )}
              </div>

              {/* Module Title */}
              <InlineEditable
                value={module.title}
                onSave={(newTitle) => onUpdateModule({ title: newTitle })}
                placeholder="Enter module title..."
                textClassName="text-lg sm:text-xl font-bold text-neutral-900 dark:text-neutral-50 tracking-tight"
                inputClassName="text-lg sm:text-xl font-bold"
              />

              {/* Module Description */}
              <InlineEditable
                value={module.description}
                onSave={(newDesc) => onUpdateModule({ description: newDesc })}
                placeholder="Click to add module overview & objectives..."
                multiline={true}
                textClassName="text-sm text-neutral-600 dark:text-neutral-400 leading-relaxed"
                inputClassName="text-sm"
              />
            </div>
          </div>

          {/* Module Action Controls */}
          <div className="flex items-center gap-1.5 flex-shrink-0">
            <button
              onClick={onAddTopic}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-neutral-100 hover:bg-[#EC8601] text-neutral-800 hover:text-white dark:bg-neutral-800 dark:text-neutral-200 dark:hover:bg-[#EC8601] transition-all shadow-sm"
              title="Add a new topic inside this module"
            >
              <Plus className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Add Topic</span>
            </button>

            {/* Delete Module button with soft confirmation */}
            {showDeleteConfirm ? (
              <div className="flex items-center gap-1 p-1 bg-red-50 dark:bg-red-950/40 border border-red-200 rounded-lg animate-in fade-in duration-150">
                <span className="text-[11px] font-medium text-red-700 dark:text-red-300 px-1">
                  Delete Module?
                </span>
                <button
                  onClick={() => {
                    setShowDeleteConfirm(false);
                    onDeleteModule();
                  }}
                  className="px-2 py-0.5 rounded bg-red-600 hover:bg-red-700 text-white text-[11px] font-medium transition-colors"
                >
                  Yes
                </button>
                <button
                  onClick={() => setShowDeleteConfirm(false)}
                  className="px-1.5 py-0.5 rounded text-neutral-600 dark:text-neutral-300 hover:bg-neutral-200 dark:hover:bg-neutral-800 text-[11px] transition-colors"
                >
                  No
                </button>
              </div>
            ) : (
              <button
                onClick={() => setShowDeleteConfirm(true)}
                className={`p-1.5 rounded-lg text-neutral-400 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950/40 transition-all ${
                  isHovered ? "opacity-100" : "opacity-0 group-hover:opacity-70"
                }`}
                title="Delete this entire module"
                aria-label="Delete this entire module"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Module Content (List of Topics) */}
      {!isCollapsed && (
        <div className="p-5 sm:p-6 space-y-4 bg-white dark:bg-neutral-900">
          {module.topics.length === 0 ? (
            <div className="py-8 px-4 rounded-xl border-2 border-dashed border-neutral-200 dark:border-neutral-800 text-center bg-neutral-50/50 dark:bg-neutral-900/30">
              <AlertCircle className="w-8 h-8 mx-auto text-neutral-400 mb-2 opacity-60" />
              <p className="text-sm font-medium text-neutral-700 dark:text-neutral-300">
                This module currently has no topics.
              </p>
              <p className="text-xs text-neutral-500 dark:text-neutral-400 mt-1 max-w-sm mx-auto">
                Break this module down into concrete thematic units by adding topics.
              </p>
              <button
                onClick={onAddTopic}
                className="mt-3 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-[#EC8601] text-white hover:bg-[#d67700] transition-colors shadow-sm"
              >
                <Plus className="w-3.5 h-3.5" />
                Add First Topic
              </button>
            </div>
          ) : (
            <div className="space-y-4">
              {module.topics.map((topic, topIdx) => (
                <TopicCard
                  key={topic.id}
                  topic={topic}
                  topicIndex={topIdx}
                  moduleId={module.id}
                  onUpdateTopic={(updates) => onUpdateTopic(topic.id, updates)}
                  onDeleteTopic={() => onDeleteTopic(topic.id)}
                  onToggleCollapse={() => onToggleTopicCollapse(topic.id)}
                  onAddLesson={() => onAddLesson(topic.id)}
                  onUpdateLesson={(lessonId, updates) =>
                    onUpdateLesson(topic.id, lessonId, updates)
                  }
                  onDeleteLesson={(lessonId) =>
                    onDeleteLesson(topic.id, lessonId)
                  }
                />
              ))}

              {/* Bottom "+ Add Topic" quick button */}
              <button
                onClick={onAddTopic}
                className="w-full py-2.5 px-4 rounded-xl border border-dashed border-neutral-200 hover:border-[#EC8601] dark:border-neutral-800 text-neutral-500 hover:text-[#EC8601] dark:text-neutral-400 dark:hover:text-[#EC8601] text-xs font-semibold flex items-center justify-center gap-2 transition-all hover:bg-[#EC8601]/5"
              >
                <Plus className="w-4 h-4 text-[#EC8601]" />
                <span>Add Topic to {module.title.split("—")[0] || "Module"}</span>
              </button>
            </div>
          )}
        </div>
      )}

      {/* Collapsed summary preview */}
      {isCollapsed && module.topics.length > 0 && (
        <div className="px-6 py-2.5 bg-neutral-50/60 dark:bg-neutral-900/60 border-t border-neutral-100 dark:border-neutral-800/80 flex items-center justify-between text-xs text-neutral-500">
          <span className="truncate max-w-md">
            Contains: {module.topics.map((t) => t.title.split("—")[0].trim()).join(", ")}
          </span>
          <button
            onClick={onToggleCollapse}
            className="text-[#EC8601] hover:underline font-medium ml-2 flex-shrink-0"
          >
            Show {module.topics.length} topics
          </button>
        </div>
      )}
    </div>
  );
}
