"use client";

import React, { useState } from "react";
import { Topic, Lesson } from "@/types/curriculum";
import { LessonRow } from "./LessonRow";
import { InlineEditable } from "./InlineEditable";
import {
  ChevronDown,
  ChevronRight,
  Plus,
  Trash2,
  Sparkles,
  Layers,
} from "lucide-react";

interface TopicCardProps {
  topic: Topic;
  topicIndex: number;
  moduleId: string;
  onUpdateTopic: (updates: Partial<Pick<Topic, "title" | "description">>) => void;
  onDeleteTopic: () => void;
  onToggleCollapse: () => void;
  onAddLesson: () => void;
  onUpdateLesson: (
    lessonId: string,
    updates: Partial<Pick<Lesson, "title" | "description">>
  ) => void;
  onDeleteLesson: (lessonId: string) => void;
}

export function TopicCard({
  topic,
  topicIndex,
  moduleId,
  onUpdateTopic,
  onDeleteTopic,
  onToggleCollapse,
  onAddLesson,
  onUpdateLesson,
  onDeleteLesson,
}: TopicCardProps) {
  const [isHovered, setIsHovered] = useState(false);
  const isCollapsed = topic.isCollapsed ?? false;

  return (
    <div
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className="relative rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50/70 dark:bg-neutral-900/40 p-4 transition-all duration-150 hover:border-neutral-300 dark:hover:border-neutral-700"
    >
      {/* Left visual accent indicator */}
      <div className="absolute left-0 top-3 bottom-3 w-1 bg-neutral-300 dark:bg-neutral-700 rounded-r transition-colors group-hover:bg-[#EC8601]" />

      {/* Topic Header */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-2.5 flex-grow min-w-0">
          {/* Collapse/Expand button */}
          <button
            onClick={onToggleCollapse}
            className="mt-1 p-1 rounded hover:bg-neutral-200/80 dark:hover:bg-neutral-800 text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-100 transition-colors flex-shrink-0"
            title={isCollapsed ? "Expand topic" : "Collapse topic"}
            aria-label={isCollapsed ? "Expand topic" : "Collapse topic"}
          >
            {isCollapsed ? (
              <ChevronRight className="w-4 h-4" />
            ) : (
              <ChevronDown className="w-4 h-4" />
            )}
          </button>

          <div className="flex-grow min-w-0 space-y-1">
            <div className="flex items-center gap-2 flex-wrap">
              {/* Topic Title */}
              <div className="flex-grow min-w-0">
                <InlineEditable
                  value={topic.title}
                  onSave={(newTitle) => onUpdateTopic({ title: newTitle })}
                  placeholder="Enter topic title..."
                  textClassName="text-base font-semibold text-neutral-900 dark:text-neutral-100 tracking-tight"
                  inputClassName="text-base font-semibold"
                />
              </div>

              {/* Lesson count badge */}
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium bg-neutral-200/60 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-300 select-none flex-shrink-0">
                <Layers className="w-3 h-3 text-neutral-400" />
                {topic.lessons.length} {topic.lessons.length === 1 ? "lesson" : "lessons"}
              </span>

              {/* Inferred badge */}
              {topic.isInferred && (
                <span
                  title="This topic was inferred & generated by AI based on module context"
                  className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border border-amber-200/60 dark:border-amber-800/40 select-none flex-shrink-0"
                >
                  <Sparkles className="w-2.5 h-2.5 text-[#EC8601]" />
                  AI Inferred
                </span>
              )}
            </div>

            {/* Topic Description */}
            <InlineEditable
              value={topic.description}
              onSave={(newDesc) => onUpdateTopic({ description: newDesc })}
              placeholder="Click to add topic description..."
              multiline={true}
              textClassName="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed"
              inputClassName="text-xs"
            />
          </div>
        </div>

        {/* Action buttons (Add lesson & Delete topic) */}
        <div className="flex items-center gap-1 flex-shrink-0">
          <button
            onClick={onAddLesson}
            className="flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-neutral-700 dark:text-neutral-200 hover:text-[#EC8601] hover:bg-[#EC8601]/10 transition-colors"
            title="Add lesson to this topic"
          >
            <Plus className="w-3.5 h-3.5 text-[#EC8601]" />
            <span className="hidden sm:inline">Add Lesson</span>
          </button>

          <button
            onClick={onDeleteTopic}
            className={`p-1.5 rounded text-neutral-400 hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950/40 transition-all ${
              isHovered ? "opacity-100" : "opacity-0 group-hover:opacity-70"
            }`}
            title="Delete topic"
            aria-label="Delete topic"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Expanded Topic Content: Lessons List */}
      {!isCollapsed && (
        <div className="mt-3.5 pl-6 sm:pl-7 border-l-2 border-dashed border-neutral-200 dark:border-neutral-800 space-y-2.5">
          {topic.lessons.length === 0 ? (
            <div className="py-3 px-4 rounded-lg border border-dashed border-neutral-200 dark:border-neutral-800 text-center bg-white/40 dark:bg-neutral-900/20">
              <p className="text-xs text-neutral-500 dark:text-neutral-400">
                No lessons in this topic yet.
              </p>
              <button
                onClick={onAddLesson}
                className="mt-1.5 inline-flex items-center gap-1 text-xs font-medium text-[#EC8601] hover:underline"
              >
                <Plus className="w-3 h-3" />
                Add the first lesson
              </button>
            </div>
          ) : (
            topic.lessons.map((lesson, lesIdx) => (
              <LessonRow
                key={lesson.id}
                lesson={lesson}
                index={lesIdx}
                moduleId={moduleId}
                topicId={topic.id}
                onUpdate={(updates) => onUpdateLesson(lesson.id, updates)}
                onDelete={() => onDeleteLesson(lesson.id)}
              />
            ))
          )}

          {/* "+ Add Lesson" bottom quick link */}
          {topic.lessons.length > 0 && (
            <button
              onClick={onAddLesson}
              className="w-full py-1.5 px-3 rounded border border-dashed border-neutral-200 hover:border-[#EC8601]/50 dark:border-neutral-800 text-neutral-500 hover:text-[#EC8601] dark:text-neutral-400 dark:hover:text-[#EC8601] text-xs font-medium flex items-center justify-center gap-1.5 transition-all hover:bg-[#EC8601]/5"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Add Lesson</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
}
